#!/bin/bash

# Skrypt do przetwarzania wyciętych map miast dla OSRM
# Użycie: ./prepare-city-osrm.sh [city] [profile]
# Przykład: ./prepare-city-osrm.sh krakow foot

set -e

CITY=${1}
PROFILE=${2:-foot}
DATA_DIR="./osrm-data"
MAP_FILE="$DATA_DIR/${CITY}.osm.pbf"
OUTPUT_BASE="${CITY}-${PROFILE}"  # e.g., krakow-foot

if [ -z "$CITY" ]; then
    echo "Użycie: ./prepare-city-osrm.sh [city] [profile]"
    echo ""
    echo "Przykład: ./prepare-city-osrm.sh krakow foot"
    exit 1
fi

if [ ! -f "$MAP_FILE" ]; then
    echo "Błąd: Plik mapy nie istnieje: $MAP_FILE"
    echo "Najpierw wytnij mapę miasta: ./scripts/extract-city.sh [region] $CITY"
    exit 1
fi

echo "Przetwarzanie mapy miasta: $CITY z profilem: $PROFILE"
echo ""

# Extract
echo "Krok 1/2: Extract..."
docker run -t -v "$(pwd)/osrm-data:/data" ghcr.io/project-osrm/osrm-backend:latest \
    osrm-extract -p /opt/$PROFILE.lua /data/${MAP_FILE##*/}

# Rename extracted files to include profile suffix (only if not already renamed)
if [ ! -f "$DATA_DIR/${OUTPUT_BASE}.osrm" ]; then
    echo "Renaming extracted files to include profile suffix..."
    for ext in osrm osrm.names osrm.restrictions osrm.fileIndex osrm.properties osrm.timestamp osrm.datasource_names osrm.edges osrm.geometry osrm.icd osrm.maneuver_overrides osrm.nbg_nodes osrm.ebg_nodes osrm.turn_weight_penalties osrm.turn_duration_penalties osrm.turn_penalties_index osrm.enw osrm.ebg osrm.cnbg osrm.cnbg_to_ebg; do
        if [ -f "$DATA_DIR/${CITY}.${ext}" ]; then
            mv "$DATA_DIR/${CITY}.${ext}" "$DATA_DIR/${OUTPUT_BASE}.${ext}" 2>/dev/null || true
        fi
    done
fi

# Contract (dla CH - domyślny algorytm OSRM)
echo "Krok 2/2: Contract..."
docker run -t -v "$(pwd)/osrm-data:/data" ghcr.io/project-osrm/osrm-backend:latest \
    osrm-contract /data/${OUTPUT_BASE}.osrm

# Copy legacy files (ramIndex, tld, tls) if they don't exist
# These files are required by osrm-routed but are only generated by older OSRM versions
# We copy them from the old krakow.osrm as a workaround
if [ ! -f "$DATA_DIR/${OUTPUT_BASE}.osrm.ramIndex" ]; then
    echo "Copying legacy files (ramIndex, tld, tls) for compatibility..."
    if [ -f "$DATA_DIR/krakow.osrm.ramIndex" ]; then
        for ext in ramIndex tld tls; do
            cp "$DATA_DIR/krakow.osrm.$ext" "$DATA_DIR/${OUTPUT_BASE}.osrm.$ext" 2>/dev/null || true
        done
    else
        echo "Warning: Legacy files not found in krakow.osrm - some profiles may not work"
    fi
fi

echo ""
echo "✓ Przetwarzanie zakończone pomyślnie!"
echo ""
echo "Pliki OSRM dla miasta $CITY (profil: $PROFILE) są gotowe."
echo "Uruchom serwer: ./scripts/run-city-server.sh $CITY $PROFILE"
