/**
 * Export Service
 * Handles exporting routes to various formats (GeoJSON, PDF)
 */

import {
  Route,
  Waypoint,
  Coordinate,
  RoutingProfile,
} from '../types/route.types';
import { NavigationInstruction } from '../services/osrm.service';

export interface GeoJSONFeatureCollection {
  type: 'FeatureCollection';
  features: GeoJSONFeature[];
}

export interface GeoJSONFeature {
  type: 'Feature';
  properties: Record<string, unknown>;
  geometry: {
    type: 'LineString' | 'Point';
    coordinates: Coordinate[] | Coordinate;
  };
}

export interface ExportOptions {
  cityName?: string;
  profile?: RoutingProfile;
  profileName?: string;
}

/**
 * Format distance for display
 */
export function formatDistance(meters: number): string {
  if (meters < 1000) {
    return `${Math.round(meters)} m`;
  }
  return `${(meters / 1000).toFixed(2)} km`;
}

/**
 * Format duration for display
 */
export function formatDuration(seconds: number): string {
  const minutes = Math.round(seconds / 60);
  if (minutes < 60) {
    return `${minutes} min`;
  }
  const hours = Math.floor(minutes / 60);
  const remainingMinutes = minutes % 60;
  return `${hours} godz ${remainingMinutes} min`;
}

/**
 * Export Service class
 */
class ExportService {
  /**
   * Export route to GeoJSON format
   */
  exportToGeoJSON(
    route: Route,
    waypoints: Waypoint[],
    options: ExportOptions = {}
  ): GeoJSONFeatureCollection {
    const {
      cityName = 'unknown',
      profile = 'foot',
      profileName = 'Pieszo',
    } = options;

    const features: GeoJSONFeature[] = [];

    // Add route line
    features.push({
      type: 'Feature',
      properties: {
        name: 'GuideTrackee Route',
        description: 'Walking tour route generated by GuideTrackee Routes',
        timestamp: new Date().toISOString(),
        city: cityName,
        profile,
        profileName,
        distance: route.distance,
        duration: route.duration,
        distanceFormatted: formatDistance(route.distance),
        durationFormatted: formatDuration(route.duration),
      },
      geometry: {
        type: 'LineString',
        coordinates: route.coordinates,
      },
    });

    // Add waypoint markers
    waypoints.forEach((waypoint, index) => {
      features.push({
        type: 'Feature',
        properties: {
          name: `Punkt ${index + 1}`,
          address: waypoint.address || '',
          order: index + 1,
          markerType:
            index === 0
              ? 'start'
              : index === waypoints.length - 1
              ? 'end'
              : 'waypoint',
        },
        geometry: {
          type: 'Point',
          coordinates: waypoint.coordinate,
        },
      });
    });

    return {
      type: 'FeatureCollection',
      features,
    };
  }

  /**
   * Download GeoJSON as file
   */
  downloadGeoJSON(
    route: Route,
    waypoints: Waypoint[],
    options: ExportOptions = {}
  ): void {
    const geojson = this.exportToGeoJSON(route, waypoints, options);
    const jsonString = JSON.stringify(geojson, null, 2);
    const blob = new Blob([jsonString], { type: 'application/geo+json' });

    const timestamp = new Date()
      .toISOString()
      .replace(/[:.]/g, '-')
      .slice(0, -5);
    const filename = `guidetrackee-route-${timestamp}.geojson`;

    this.downloadBlob(blob, filename);
  }

  /**
   * Generate PDF content for route instructions
   * Returns the document definition for pdfMake
   */
  generatePDFDefinition(
    route: Route,
    waypoints: Waypoint[],
    instructions: NavigationInstruction[],
    options: ExportOptions = {}
  ): unknown {
    const { cityName = '', profileName = 'Pieszo' } = options;

    const instructionsContent = instructions.map((instruction, index) => ({
      columns: [
        {
          width: 25,
          text: `${index + 1}.`,
          bold: true,
          color: '#ff6600',
          fontSize: 10,
        },
        {
          width: '*',
          text: instruction.text,
          fontSize: 10,
          margin: [0, 0, 10, 0],
        },
        {
          width: 50,
          text: formatDistance(instruction.distance),
          fontSize: 9,
          color: '#666666',
          alignment: 'right',
        },
      ],
      margin: [0, 3, 0, 3],
    }));

    // PDF document definition (pdfMake format)
    return {
      pageSize: 'A4',
      pageMargins: [40, 60, 40, 60],

      header: {
        columns: [
          {
            text: 'GuideTrackee Routes',
            fontSize: 14,
            bold: true,
            color: '#ff6600',
            margin: [40, 20, 0, 0],
          },
          {
            text: new Date().toLocaleDateString('pl-PL'),
            fontSize: 10,
            color: '#666666',
            alignment: 'right',
            margin: [0, 22, 40, 0],
          },
        ],
      },

      content: [
        // Title
        {
          text: 'Instrukcje nawigacyjne',
          fontSize: 20,
          bold: true,
          margin: [0, 0, 0, 20],
        },

        // Route info
        {
          columns: [
            {
              width: '*',
              stack: [
                { text: 'Dystans', fontSize: 10, color: '#666666' },
                {
                  text: formatDistance(route.distance),
                  fontSize: 14,
                  bold: true,
                },
              ],
            },
            {
              width: '*',
              stack: [
                { text: 'Czas', fontSize: 10, color: '#666666' },
                {
                  text: formatDuration(route.duration),
                  fontSize: 14,
                  bold: true,
                },
              ],
            },
            {
              width: '*',
              stack: [
                { text: 'Profil', fontSize: 10, color: '#666666' },
                { text: profileName, fontSize: 14, bold: true },
              ],
            },
            cityName
              ? {
                  width: '*',
                  stack: [
                    { text: 'Miasto', fontSize: 10, color: '#666666' },
                    { text: cityName, fontSize: 14, bold: true },
                  ],
                }
              : {},
          ],
          margin: [0, 0, 0, 20],
        },

        // Divider
        {
          canvas: [
            {
              type: 'line',
              x1: 0,
              y1: 0,
              x2: 515,
              y2: 0,
              lineWidth: 1,
              lineColor: '#eeeeee',
            },
          ],
          margin: [0, 0, 0, 15],
        },

        // Waypoints summary
        {
          text: `Punkty trasy (${waypoints.length})`,
          fontSize: 12,
          bold: true,
          margin: [0, 0, 0, 10],
        },
        ...waypoints.map((wp, index) => ({
          columns: [
            {
              width: 25,
              text: `${index + 1}.`,
              bold: true,
              color:
                index === 0
                  ? '#22c55e'
                  : index === waypoints.length - 1
                  ? '#ef4444'
                  : '#ff6600',
              fontSize: 10,
            },
            {
              width: '*',
              text:
                wp.address ||
                `${wp.coordinate[1].toFixed(6)}, ${wp.coordinate[0].toFixed(
                  6
                )}`,
              fontSize: 10,
            },
          ],
          margin: [0, 2, 0, 2],
        })),

        // Divider
        {
          canvas: [
            {
              type: 'line',
              x1: 0,
              y1: 0,
              x2: 515,
              y2: 0,
              lineWidth: 1,
              lineColor: '#eeeeee',
            },
          ],
          margin: [0, 15, 0, 15],
        },

        // Instructions
        {
          text: 'Kroki nawigacji',
          fontSize: 12,
          bold: true,
          margin: [0, 0, 0, 10],
        },
        ...instructionsContent,
      ],

      footer: (currentPage: number, pageCount: number) => ({
        columns: [
          {
            text: 'Wygenerowano przez GuideTrackee Routes',
            fontSize: 8,
            color: '#999999',
            margin: [40, 0, 0, 0],
          },
          {
            text: `Strona ${currentPage} z ${pageCount}`,
            fontSize: 8,
            color: '#999999',
            alignment: 'right',
            margin: [0, 0, 40, 0],
          },
        ],
      }),

      defaultStyle: {
        font: 'Roboto',
      },
    };
  }

  /**
   * Download blob as file
   */
  private downloadBlob(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;

    document.body.appendChild(link);
    link.click();

    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Share route using Web Share API (for mobile)
   */
  async shareRoute(
    route: Route,
    waypoints: Waypoint[],
    options: ExportOptions = {}
  ): Promise<boolean> {
    if (!navigator.share) {
      console.warn('Web Share API not supported');
      return false;
    }

    const geojson = this.exportToGeoJSON(route, waypoints, options);
    const jsonString = JSON.stringify(geojson, null, 2);
    const blob = new Blob([jsonString], { type: 'application/geo+json' });
    const file = new File([blob], 'route.geojson', {
      type: 'application/geo+json',
    });

    try {
      await navigator.share({
        title: 'GuideTrackee Route',
        text: `Trasa: ${formatDistance(route.distance)}, ${formatDuration(
          route.duration
        )}`,
        files: [file],
      });
      return true;
    } catch (error) {
      if ((error as Error).name !== 'AbortError') {
        console.error('Share failed:', error);
      }
      return false;
    }
  }
}

export const exportService = new ExportService();
